[tools]
# Go version required by the project
go = "1.22.4"

# Optional: AWS CLI for managing profiles and SSO
awscli = "latest"

# Optional: tmux for xpanes multi-instance support
# xpanes can be installed via: brew install xpanes